### ISSUE TITLE
Update minimum python version to 3.9

### ISSUE THREAD

**Issue by lubbersnick** [lanl/hippynn#55]
latest updates break with python<3.9 but it is time to move on.

**Comment by lubbersnick** [comment]
@tautomer @EShinkle1 Let's work together for this. Not quite sure why I can't add you as assignees. You should be able to push changes to the update_python_39 branch of this repository, though.

**Comment by tautomer** [comment]
Just accepted your invitation. Maybe because I was not a collaborator of the repo.

**Comment by lubbersnick** [comment]
@bnebgen-LANL will it break any important workflows if we stop supporting python 3.7 and 3.8?
