### ISSUE TITLE
Installation issues for python version 3.12

### ISSUE THREAD

**Issue by sakibmatin** [lanl/hippynn#61]
hippynn is not compatible with python3 version 3.12 due to versioneer.py

Installation works with 
`conda create -n test_env311 python=3.11 numpy scipy matplotlib pytorch cudatoolkit ase numba python-graphviz tqdm numba python-graphviz tqdm cupy cython -c conda-forge`

Installation fails with 
`conda create -n test_env312 python=3.12 numpy scipy matplotlib pytorch cudatoolkit ase numba python-graphviz tqdm numba python-graphviz tqdm cupy cython -c conda-forge`

**Comment by lubbersnick** [comment]
Thanks for reporting this, we will look into it! Before pytorch was not supporting 3.12 but it looks like it is now, we will check on how to deal with versioneer. If you find anything more out please feel free to report it here.

**Comment by lubbersnick** [comment]
According to https://github.com/warner/python-spake2/issues/13 and https://github.com/dask/dask-image/pull/357 we just need to re-deploy versioneer.
